### ISSUE TITLE
Issues with hover logic on menu buttons

### ISSUE THREAD

**Issue by harshavb** [harshavb/piously#31] opened 2020-11-27 13:41 UTC
If a user stops hovering over a menu button by rehovering over the logo, it works fine. However, if a user stops hovering over a menu button by hovering over the background, things break.

**Comment by ben9583** [comment] 2020-11-27 16:08
Unable to reproduce locally; can you send a clip of it happening?

**Comment by harshavb** [comment] 2020-11-27 16:28
Pull.

**Comment by ben9583** [comment] 2020-11-28 19:48
Fixed with 93b04d4. Closing

**Closed by ben9583** 2020-11-28 19:48 UTC
